### ISSUE TITLE
timing issue - geojson data sometimes not loading correctly

### ISSUE THREAD

**Issue by j-gimbel** [vue-leaflet/vue-leaflet#108]
Hello, I am a quite newbie on github and vue3, so I say sorry in advance if this is not the rightr way to ask for help.
Maybe I have a similar issue as discussed in #48 that sometimes the leaflet code from leaflet/src... and sometimes from @vue-leaflet/vue-leaflet is loaded. 
My error is a different one in the GEOJson module responding with a strange ("not a valid geojson") - but I simply refresh the page and then it works - then again not, so the geojson file is not the culprit (and I validated the file with geojson linters).

I also know where my problem lies, I think.
I am using 
`import { LMap, LTileLayer, LGeoJson } from "@vue-leaflet/vue-leaflet";` (as explained in the demo-project, I think this is outdated)
whereas I should use (as explained in the readme) : 
`import { LMap, LTileLayer, LGeoJson } from "./../../components";`
But this gives:
`Failed to resolve import "./../../components"`

I am using vite and vue3 (with the composition API) for the first time and this seems to be a relative path import issue. 
Sadly vite does not have a "root" path "@/..." . 

So how can I adapt my code to make it work ? This is my code:

```
<template>
  <div v-if="loaded" class="container-fluid vh-100">
    <div class="row vh-100">
      <div class="col-9">
        <l-map :zoom="7" :center="[51.4, 9.0]">
          <l-geo-json
            v-if="loaded"
            :geojson="geojson"
            :options="geojsonOptions"
          />
          <l-tile-layer
            url="https://cartodb-basemaps-{s}.global.ssl.fastly.net/light_all/{z}/{x}/{y}.png"
          ></l-tile-layer>
        </l-map>
      </div>

      <div class="col-3">
        <h3>Info</h3>
        Landkreis:
        <span> {{ lkName }}</span>
      </div>
    </div>
  </div>
</template>
<script>
import { ref, onMounted, watch } from "vue";
//import { LMap, LTileLayer, LGeoJson } from "@vue-leaflet/vue-leaflet";
import { LMap, LTileLayer, LGeoJson } from "./../../components";
import "leaflet/dist/leaflet.css";
export default {
  components: {
    LMap,
    LTileLayer,
    LGeoJson,
  },

  data() {
    return {
      zoom: 6,
      geojsonOptions: {
        onEachFeature: this.onEachFeature,
        style: this.setGeoJsonStyle,
      },
      loaded: false,
      lkName: "",
    };
  },

  mounted() {
    this.loaded = true;
  },
  watch: {
    selectedLayer(o, n) {
      console.log(o, n, this.selectedLayer);
    },
    hoveredLayer(o, n) {
      console.log(o, n, this.hoveredLayer);
      this.lkName = this.hoveredLayer.feature.properties.name;
    },
    geoJsonloaded(o, n) {
      console.log("loaded!");
      this.loaded = this.geoJsonloaded;
    },
  },

  setup() {
    const defaultStyle = {
      weight: 1,
      color: "#808080",
    };

    const hoverStyle = {
      color: "#333",
      weight: 2,
    };

    const selectedStyle = {
      color: "#cc0000",
      weight: 2,
    };

    const selectedLayer = ref(null);
    const hoveredLayer = ref(null);
    const geoJsonloaded = ref(false);
    const geojson = ref({});
    const getGeojson = async () => {
      var myHeaders = new Headers();
      myHeaders.append("pragma", "no-cache");
      myHeaders.append("cache-control", "no-cache");
      myHeaders.append("Content-Type", "application/json");
      myHeaders.append("Accept", "application/json");
      var myInit = {
        method: "GET",
        headers: myHeaders,
      };
      var myRequest = new Request("landkreise_rki.geojson");
      fetch(myRequest, myInit)
        .then((response) => response.json())
        .then(function (geojson_data) {
          console.log(geojson_data);
          geojson.value = geojson_data;
          geoJsonloaded.value = true;
          console.log(mylog.value);
          return geojson_data;
        });
    };

    const whenClicked = (e) => {
      //console.log("whenClicked", e);
      var layer = e.target;
      if (selectedLayer.value != null) {
        selectedLayer.value.setStyle(defaultStyle);
        if (
          selectedLayer.value.feature.properties.id ==
          layer.feature.properties.id
        ) {
          selectedLayer.value = null;
          return;
        }
      }
      selectedLayer.value = layer;
      console.log(selectedLayer.value);
      layer.setStyle(selectedStyle);
    };

    const whenMouseover = (e) => {
      //console.log("whenMouseover", e);
      var layer = e.target;
      hoveredLayer.value = layer;
      if (selectedLayer.value != null) {
        if (
          selectedLayer.value.feature.properties.id ==
          layer.feature.properties.id
        ) {
          return;
        }
      }
      layer.setStyle(hoverStyle);
    };

    const whenMouseout = (e) => {
      console.log("whenMouseout", e);
      var layer = e.target;
      if (selectedLayer.value != null) {
        console.log(selectedLayer);
        if (
          selectedLayer.value.feature.properties.id ==
          layer.feature.properties.id
        ) {
          return;
        }
      }
      layer.setStyle(defaultStyle);
    };

    const onEachFeature = (feature, layer) => {
      //console.log(feature, layer);
      //bind click
      layer.on({
        click: whenClicked,
        mouseover: whenMouseover,
        mouseout: whenMouseout,
      });
    };

    const setGeoJsonStyle = (e) => {
      return { color: "#808080", weight: 1 };
    };

    onMounted(getGeojson); // on `mounted` call `getUserRepositories`

    return {
      geojson,
      getGeojson,
      onEachFeature,
      setGeoJsonStyle,
      whenClicked,
      selectedLayer,
      hoveredLayer,
      geoJsonloaded,
      mylog,
    };
  },
};
</script>
<style>
#map {
  position: relative;
  width: 100%;
  height: 100%;
  left: 0%;
  top: 0%;
}
</style>
```

**Comment by j-gimbel** [comment]
OK, sorry, not enough sleep - but I keep it here, maybe it helps others.
Of course you can use absolute pathes with vite like this:
```
import {
  LMap,
  LTileLayer,
  LGeoJson,
} from "@vue-leaflet/vue-leaflet/src/components";
```

**Comment by j-gimbel** [comment]
I fixed the import statement to 
```
import {
  LMap,
  LTileLayer,
  LGeoJson,
} from "@vue-leaflet/vue-leaflet/src/components";
```

But i still have the timing issue that sometimes the wrong leflet code is loaded and the following items appear in the dev console:

```
[Vue warn]: Unhandled error during execution of mounted hook 
  at <LGeoJson key=0 geojson= 
Object {  }
 options= 
Object { onEachFeature: onEachFeature(feature, layer), style: setGeoJsonStyle(e) }
 > 
  at <LMap zoom=7 center= 
Array [ 51.4, 9 ]
 > 
  at <Map> 
  at <App> runtime-core.esm-bundler.js:38:16

```

```
Uncaught (in promise) Error: Invalid GeoJSON object.
    geometryToLayer GeoJSON.js:221
    addData GeoJSON.js:117
    initialize GeoJSON.js:92
    NewClass Class.js:22
    geoJSON GeoJSON.js:439
    setup LGeoJson.vue:20
GeoJSON.js:221:8

```

GeoJSON.js is in node_modules/leaflet/src/layer/GeoJSON.js


When I remove the fetch and insert the geojson as an object it works. 
So somehow I seem to have a reactivity/async issue here ?

**Comment by mikeu** [comment]
Hi @j-gimbel , welcome! This is a perfectly acceptable place to ask questions, at least unless we decide to set up [discussions](https://docs.github.com/en/discussions) on the repo, in which case that would become more appropriate if not reporting an actual bug, feature request, etc. Or you can join our [discord](https://discord.gg/uVZAfUf) to ask questions in the #help-wanted channel and chat a little more real-time with anyone who's online at the time. It's currently a pretty small group, but steadily growing!

That said, I must apologize for some of the troubles you are having, as they are at least partly due to a mistake you've now pointed out in the readme! The relative path to the components was a red herring, and in fact is only expected to work within the demo code of this repository, not of others that import it. I'll try to get that fixed ASAP.

So first off, it should be correct to simply `import { LMap, LTileLayer, LGeoJson } from "@vue-leaflet/vue-leaflet"`. Importing from the components directory as you have should also work though, as far as I know. So while that's not required, it's also likely not the source of the problem.

To focus on getting you up and running first, what happens if you change the conditional on your `l-geojson` component to `<l-geojson v-if="geoJsonloaded" ...>`, which won't be `true` until after the GeoJSON has in fact loaded? Right now, you're setting `loaded` to `true` as soon as the component mounts and using that as the conditional, which is using it before it's ready I think.

---

Whether or not that works, I think you're likely also going to run into further difficulty debugging your component while it continues to mix the Vue 2-style component definition with the Vue 3 composition API. Either approach is perfectly valid under Vue 3, but I don't know that mixing them is recommended in a single component. Feel free to ignore the rest of this, and take it with a grain of salt as I'm also still new to the composition API. But in case you're interested, here are a couple of suggestions...

First, pick either the "standard" Vue 2 approach of including `data`, `mounted`, etc., as properties/methods in the object you're creating, _or_ the composition API approach of calling Vue's `onMounted` etc. functions inside `setup`, which should return `ref`s for the data properties you want access to in the template. This should help to avoid confusion around issues such as the fact that in the `mounted()` hook, the `loaded` property is set to `true`, even though it is only in the slightly different `onMounted()` hook—which should execute at basically the same time, though I'm not sure in which order—that the async loading is even _started_.

Also, you really probably don't want `watch` properties here, but rather [`computed`](https://v3.vuejs.org/guide/computed.html#computed-properties) ones. The best example of this is for your `lkName` property. Instead of having `lkName` as a property that you update in a watcher on the `hoveredLayer` property, you'll likely be better served by a computed property named `lkName` that simply returned `hoveredLayer.feature.properties.name`.

In the SFC style, this would like like
```js
export default {
  // ...everything else
  computed: {
    lkName () { return this.hoveredLayer.feature.properties.name; }
  }
}
```
whereas using the composition API it would be more like
```js
import { computed } from "vue";
export default {
  // ...components etc.
  setup () {
    const hoveredLayer = ref(null);
    const lkName = computed(() => hoveredLayer && hoveredLayer.feature.properties.name);
    // ...everything else
    return { hoveredLayer, lkName, /* etc. */ };
  }
}
```

**Comment by j-gimbel** [comment]
Hello @mikeu , thank you for the quick and extensive response.
The part 
`<l-geojson v-if="geoJsonloaded" ...>` fixed it. 
I will now update my code following your suggestions.
