### ISSUE TITLE
A release with 3.2 support?

### ISSUE THREAD

**Issue by baybal** [vue-leaflet/vue-leaflet#151]
Hello,

Any plans on when the 3.2 compatible release will come?

**Comment by mikeu** [comment]
Hi @baybal, thank you for raising this issue. I'd love to help get this up and running, but haven't been doing much front-end work recently so haven't actually used Vue past 3.0 yet. Could you highlight what the issues are that make the current release incompatible with 3.2, or otherwise expand on the issue you're facing?

**Comment by baybal** [comment]
I just see that the dependency for the last release is set for <= 3.1. If there is no explicit API breakages, just version bumping the package deps should be enough.

**Comment by mikeu** [comment]
Ah I misunderstood what you were after, sorry. The current requirement in `package.json` is a peer dependency of `"vue": "^3.0.0"`. I just created a test app requiring ` "vue": "^3.2.0"` and `"@vue-leaflet/vue-leaflet": "^0.6.1"`, and it doesn't seem to have any issues installing, building, or running.

Where is it that you're seeing the requirement for <= 3.1?

**Comment by baybal** [comment]
Ah, it was ^3.0, my mistake

**Comment by mikeu** [comment]
No worries, sounds as if this is an easy one to close then!
