### ISSUE TITLE
Cant remove zoom buttons

### ISSUE THREAD

**Issue by GeekyMonkey** [vue-leaflet/vue-leaflet#153]
I'm creating an <l-map> component without an <l-control-zoom>  But the +/- zoom buttons are appearing at the top left regardless.  I can't find a way to disable this.  If I add an <l-control-zoom> then I end up with 2 sets of zoom buttons.

**Comment by mikeu** [comment]
Hi @GeekyMonkey, you should be able to remove the default zoom control by setting the [`zoomControl`](https://leafletjs.com/reference-1.7.1.html#map-zoomcontrol) option to `false` on the map, something like
```vue
<l-map :options="{ zoomControl: false }" ...>
  ...
</l-map>
```
Let me know if the issue is that the second set of buttons is still appearing even when you're doing that.

**Comment by GeekyMonkey** [comment]
Thanks so much for your reply @mikeu 
Yes, setting it in the options like you mentioned did solve my problem. I guess I just overlooked the instructions for that.

**Comment by mikeu** [comment]
@GeekyMonkey you are welcome! Yeah, because this library is a wrapper for Leaflet and not a mapping library in its own right, we don't reproduce all of the documentation for Leaflet-specific options and features. I find it's often worth checking [their documentation](https://leafletjs.com/reference-1.7.1.html) to see how you'd do something in vanilla Leaflet, and then ideally it _just works_ to do the same thing with perhaps some Vue syntax around it. Anything that doesn't work that way is definitely worth opening an issue here for!
