### ISSUE TITLE
Map object

### ISSUE THREAD

**Issue by muzammil17** [vue-leaflet/vue-leaflet#164]
Hi how can I access the mapObject of the ref map` (this.$refs.map.mapObject) `or **leafletObject**. I am getting undefined on both things, is there anything else I have to do access this ?

**Comment by mikeu** [comment]
Hi @muzammil17 , the only guess I have without seeing any of your code or what you've already tried is that you are accessing the `leafletObject` before the map is ready to be used. Hopefully all you need to do is move the code where you access it into the map's `@ready` event handler (or anything that doesn't run until after that has fired).

If that's not enough to resolve your issue, then please provide a sample of your code, or even better a minimal working example in e.g. codesandbox, jsfiddle, or similar, and I'll try to get you up and running!

**Comment by muzammil17** [comment]
I was trying to access it on the mounted event. Now the issue is resolved I have moved the code to the ready event. 
thanks

**Comment by muzammil17** [comment]
https://user-images.githubusercontent.com/30322831/140370910-796a40f4-2780-4a00-81b0-31d7fa165faa.mp4

Why it is hanging so much in zoom in and out. It is also fetching map png every time I zoom in or out. Is there any solution for this ?

**Comment by mikeu** [comment]
If you believe there's a specific problem with the map and you are confident that it is because of vue-leaflet, and not Leaflet or your internet connection or browser speed, then please feel free to open another issue with a more detailed report of the problem.

That said, I don't really see an obvious issue in that animation -- you are very rapidly cycling through a wide range of zoom levels, and sometimes it takes the downloads a few moments to catch up. I think that is pretty normal behaviour for Leaflet. 

As for why your browser isn't caching its downloads I can't say, but I don't think that it has anything to do with vue-leaflet. Again though, if you identify an issue within this library, then please do open an issue with more details!

**Comment by pavellzubkov** [comment]
> seems to be leaflet didn't cash layer files. for smooth zoom set :zoom-animation="true" on l-map component
