### ISSUE TITLE
Support for vector layers

### ISSUE THREAD

**Issue by iBobik** [vue-leaflet/vue-leaflet#166]
Could it be configured to use vector tiles (e.g. Mapbox)?

https://github.com/Leaflet/Leaflet.VectorGrid

**Comment by mikeu** [comment]
There isn't an existing plugin for it that I'm aware of, as there is for [Vue2Leaflet](https://github.com/vue-leaflet/Vue2Leaflet) with [vue2-leaflet-vectorgrid](https://github.com/tesselo/vue2-leaflet-vectorgrid), but there shouldn't be any reason that you can't configure your own component that does the job, or even wrap it up as a plugin.

Since Leaflet.VectorGrid is itself a plugin for Leaflet and not part of its core, there wouldn't be any plans to add that functionality directly into vue-leaflet.

**Comment by iBobik** [comment]
Aha, understand.

Thank you for the link to vue2-leaflet-vectorgrid
<https://github.com/tesselo/vue2-leaflet-vectorgrid>, good for the
inspiration.


Honza Pobořil


19. 11. 2021 5:55:32, Michael Underwood ***@***.***> napsal:

**Comment by mikeu** [comment]
If you do end up publishing a plugin, please let us know and we'd be happy to link to it from here!

**Comment by lagamura** [comment]
@mikeu My search for rendering the map in an intranet environment lead me to the following:
I tried [2osm](https://switch2osm.org/serving-tiles/using-a-docker-container/), but the hardware demands for raster tiles overcomes my capacity for experimental purposes. Thus, I am leading to try vector tiles for efficiency but because I am not so advanced in customizing components, can you provide a step-guide on how I could apply a vector plugin to _vue-leaflet_ native components?

**Comment by nikbpetrov** [comment]
+1 also looking for a solution
