### ISSUE TITLE
Question: Is there a way to know when the map and markers are rendered/finished rendering?

### ISSUE THREAD

**Issue by msslgomez** [vue-leaflet/vue-leaflet#259]
Basically the title. My idea was to show a loading icon until everything is rendered, I tried using the ready event but that event fires and everything is still rendering since that event isn't really for the render part being ready. Is there some way I can do this?

**Comment by mikeu** [comment]
Since all of the rendering—and therefore completion of rendering—is handled by the underlying Leaflet instance, the only way to achieve this would be if Leaflet itself had such an event. I'm not aware of one unfortunately, but if you can find a way to accomplish what you're after in vanilla [LeafletJS](https://leafletjs.com/), then I'd be happy to help you get it working in vue-leaflet. The approach would essentially be to add an event handler to the map (e.g. `@onRenderComplete="hideSpinner"`, or whatever the hypothetical Leaflet event would be called).
