### ISSUE TITLE
Vue-leaflet LPopup does not update with prop change

### ISSUE THREAD

**Issue by sgpinkus** [vue-leaflet/vue-leaflet#266]
I'm using `Vue@3` and `@vue-leaflet/vue-leaflet@0.8.1`. I have map with some LMarkers with LPopups nested in them. I want to conditionally render the LPopup based on a boolean component state variable like this (full demo [here](https://stackblitz.com/edit/github-pfdqqj)):

```js
<script lang='ts'>
import { defineComponent } from 'vue';
import { LMap, LTileLayer, LMarker, LPopup, LControl } from '@vue-leaflet/vue-leaflet';

export default defineComponent({
  components: {
    LMap,
    LTileLayer,
    LMarker,
    LPopup,
    LControl
  },
  data(): Record<any, any> {
    return {
      mapOptions: {
        zoom: 11,
        center: [51.505, -0.09],
      },
      tileLayer: {
        url: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
        maxZoom: 19,
      },
      disablePopups: true,
    };
  },
  methods: {
    clickMarker(e: any) {
      console.log(`Click marker: disablePopups=${this.disablePopups}`);
    }
  },
});
</script>

<template>
    <v-app>
      <v-main app>
        <v-container>
          <v-row>
            <LMap style="height:100vh" :='mapOptions'>
              <LTileLayer :='tileLayer'  />
              <LControl position='topright'>
                <v-switch v-model='disablePopups' color='primary' density='comfortable'></v-switch>
              </LControl>
              <LMarker
                :lat-lng="[51.516434, -0.094414]"
                @click='clickMarker'
              >
                <LPopup v-if='!disablePopups'>
                  Disabled: {{ disablePopups }}
                  Date: {{ new Date() }}
                </LPopup>
              </LMarker>
            </LMap>
          </v-row>
        </v-container>
      </v-main>
    </v-app>
</template>
```

However, after `disablePopups` changes to false for the first time and the popup content is rendered, the popup get stuck bound to the marker with content when `disablePopups` toggles back to true. Pretty sure this is a bug in either Leaflet or the way vue-leaflet is interfacing with it. Does anyone know a work around or fix?

**Comment by mikeu** [comment]
Hi @sgpinkus , thank you for reporting this issue. Could you please revert your edits so that there actually is a bug report here, and not just an external link? Thanks! In the meantime I'm looking into this and have confirmed the behaviour as well, but not yet found a solution. The problem at the moment is that even with calling `unbindPopup` and `remove`, Leaflet still seems to be hanging onto it for some reason. I'll keep digging...

**Comment by sgpinkus** [comment]
Done. Thanks.

> The problem at the moment is that even with calling unbindPopup and remove, Leaflet still seems to be hanging onto it for some reason.

Concur. That's about as far as I got.

**Comment by mikeu** [comment]
@sgpinkus I've just released [v0.8.3](https://github.com/vue-leaflet/vue-leaflet/releases/tag/v0.8.3), which should resolve this issue. Please let me know if you're still seeing weird or unexpected behaviour!

**Comment by sgpinkus** [comment]
I have to step back a bit here. I said in issue I was using 0.8.1. I think I was actually using 0.6.1. In [this example project](https://stackblitz.com/edit/vue-leaflet-x?file=README.md) when I bump to latest (0.8.3) the marker doesn't even show up. Same for 0.8.1. I think something may have broken somewhere in 0.7-latest (random aside: I tried updating another project to 0.8.1 from 0.6.1 earlier and everything broke, never bothered investigating further)

**Comment by mikeu** [comment]
OK, I did a bit of digging, and it looks as if the (new) real problem here might be to do somehow with the LControl... Here is a [fork of your example](https://stackblitz.com/edit/vue-leaflet-x-umyy7y?file=src%2FApp.vue) where basically everything is working as I'd expect, except for the fact that toggling the value of `disablePopups` from the control with the Vuetify switch inside the map doesn't have any effect. But ignoring the switch and using the button I added below the map to toggle whether the popup is enabled is working for me.

**Comment by sgpinkus** [comment]
I'm not seeing what your seeing. From here the button and the switch work the same (In hindsight I should have cut vuetify out of the equation, sorry about that). 

What I meant by the "random aside" above is shown here -- https://stackblitz.com/edit/vue-leaflet-x-fhfmlq?file=package.json. Same project, all I did was upgrade to v0.8.1 and add `useGlobalLeaflet: false`. As you can see (hopefully) no Marker renders.

**Comment by mikeu** [comment]
Hmm, now I'm seeing some rather inconsistent behaviour with stackblitz... When I reloaded my fork this morning, it sort of half worked in that disabling the popups while open would clear the content from the popup, but not remove the balloon itself. I also still haven't found a way to get the tile layer to actually appear there and not fill the console with CORS errors. And for the random aside, indeed I don't see the marker icon, though if I hunt around for it with the mouse, the popup is there:
![image](https://user-images.githubusercontent.com/605493/218507031-2e5d9eb7-67bf-4d35-bab3-d362ad064589.png)
(It also disappears when I disable the popups.)

Here's a similar [demo on codesandbox](https://codesandbox.io/s/vl-conditional-popups-3zfxp4?file=/src/App.vue) instead. The trouble I have _there_ is that I've never figured out why it won't load the leaflet icon png, so you end up with the missing image square labelled instead, but that's a completely separate issue. As far as leaflet, Vue, and vue-leaflet are concerned the marker is there, the image for it just didn't load:
![vl-conditional-popups](https://user-images.githubusercontent.com/605493/218505481-b5ca7b58-53bc-4d9d-a10e-6f81153ef390.gif)

---

Have you seen this same behaviour locally? If so, can you share a demo repo that reproduces the problem if I clone it locally and `yarn serve` or `npm run dev` or whatever?

In the meantime, if you really need it working in stackblitz or somewhere else that it currently isn't for you, a workaround might be to move the v-if up to the LMarker, and have a v-else on an otherwise identical marker but with no popup inside it. Not ideal I know, especially if there are lots of markers, but hopefully as a temporary fix it'll do the trick.

**Comment by sgpinkus** [comment]
> Have you seen this same behaviour locally? If so, can you share a demo repo that reproduces the problem if I clone it locally and yarn serve or npm run dev or whatever?

Everything I put on stackblitz is something I've seen locally on local dev box then uploaded to stackblitz so I can easily demonstrate the issue to others. There is a download button on stackblitz that lets you download a .zip of the project (cloud ocon at the top of the left nav bar).

I havea a fix for this now. I'm just managing the popups myself (hence that Q over on discussion forum about accessing leafletObject :) - thanks again). It's working pretty well. Only issue right now is I can't (?) utilize Vue's template parser for the popup content and the popup content is semi-complex.

**Comment by mikeu** [comment]
OK, I've figured out what's going on, I think. If you flip the initial value of `disablePopups` in your example to `false`, then the whole thing should start working!

When the popups are initially enabled, there is a single child in the LMarker's default slot, and it is the LPopup, which is identified as not being content, so the marker is rendered. On the other hand, when the popups are initially disabled, there is _still_ a single child in the LMarker's default slot, but it's a comment containing `<!--v-if-->`! That is _not_ identified as not being content since it's neither a popup nor a tooltip. Therefore the marker hides the default icon in order to render whatever its slot contains... which in this case is _nothing_.

What this means is, the logic I put in place to decide whether or not to hide the default icon in favour its the LMarker's content definitely needs to be improved. This also makes me realize that the LMarker should probably also end up being reactive to its slot content—in theory you could put an LIcon inside it with a v-if, and expect it to show the default icon when the condition was false.
