### ISSUE TITLE
<l-icon> renders square when it's <div> inside of it

### ISSUE THREAD

**Issue by waptaxi** [vue-leaflet/vue-leaflet#272]
This code from the playground `<l-icon><div class="div-icon">Custom HTML icon</div></l-icon>` renders that `<div>`, but also a small square.
As I can see it is 
```
.leaflet-div-icon {
    background: #fff;
    border: 1px solid #666;
}
```
So it seems we need to remove these styles or as a temporary workaround one can use `className="leaflet-dummy-class"` on `<l-icon>` to remove .leaflet-div-icon completely from it.

**Comment by mikeu** [comment]
On closer inspection here, this is in fact Leaflet's intended output. From the [DivIcon docs](https://leafletjs.com/reference.html#divicon):

> By default, it has a 'leaflet-div-icon' CSS class and is styled as a little white square

I've updated the playground so that the unexpected result in the previous version no longer happens, but do not plan to override Leaflet's default behaviour by automatically removing it or overriding the style.
