### ISSUE TITLE
Perhaps need to handle "this._map is null" error introduced in Leaflet + Vue3

### ISSUE THREAD

**Issue by Vectorial1024** [vue-leaflet/vue-leaflet#273]
I have a map that, after the user clicks a certain position, will fly to that position+zoom level, and will also create some pins nearby using `v-for`.

Recently, I have found that randomly, map pins will fail to update their positions after the flying. They will stay on the absolute screen positions while the underlying map is being zoomed, making the pin appear in the wrong on-map locations. (They still move correctly when I pan them, but then the movement is based upon the wrong position generated after the zoom.)

I open the browser (Firefox) console to find this:

![image](https://user-images.githubusercontent.com/17726797/219299194-0b58bcb0-b0cc-4c21-8f90-8ef167ae0b4d.png)

So I searched online, and then found this:

https://stackoverflow.com/questions/65981712/uncaught-typeerror-this-map-is-null-vue-js-3-leaflet

> FWIW, this seems a new issue since Vue 3.
> ...
> Then make sure to properly unwrap / unproxy this.map before using it with Leaflet, e.g. using Vue 3 [toRaw utility function](https://v3.vuejs.org/api/basic-reactivity.html#toraw):

It suggests a workaround for this problem, but it seems this has to be done at the `vue-leaflet` library level, not library user's level.

**Comment by mikeu** [comment]
Hi @Vectorial1024 , thank you for reporting this issue! Can you confirm that this is happening with vue-leaflet [^0.8.3](https://github.com/vue-leaflet/vue-leaflet/releases/tag/v0.8.3)? That release already introduced the use of raw Leaflet objects instead of proxies.

If an update isn't enough to resolve the issue, would you be able to provide a demo that reproduces it, as a public repo, [codesandbox](codesandbox.io/), [stackblitz](https://stackblitz.com/), or similar?

**Comment by Vectorial1024** [comment]
Thank you for the info! I'll just double check this in the coming days when I update the vue-leaflet package + use it.

**Comment by Vectorial1024** [comment]
Update: it turns out I have been using 0.8.1 for a long time and did not notice that 0.8.3 was released last week. I'll just close this and then open a new issue if I find any new problems.
