### ISSUE TITLE
0.2.0 Issue with mapObject/leafletObject, Lpopup not working

### ISSUE THREAD

**Issue by Saltibarsciai** [vue-leaflet/vue-leaflet#42]
reproduction repo here: https://github.com/Saltibarsciai/vue3-leaflet-demo/blob/main/src/App.vue
PS. it's the same repo I used to show issue of icon not changing via $ref on marker 

video here: https://screenrec.com/share/2OKdZ0HazN

Quick summary:

When having $ref on <l-map> it no longer has mapObject so such things as scrollWheelZoom.disable(); and zoomControl.remove() on map ref can't be done, therefore adding custom stuff to map, for example new zoom  L.control.zoom({position: 'topright'}).addTo(this.map); won't work.

I saw new attribute on 0.2.0 leafletObject but it can't be reached on mounted no matter how much next ticks I do. (tried 5)

**Comment by Saltibarsciai** [comment]
Lpopup not working video: https://screenrec.com/share/cqA4OSQWyo

**Comment by mikeu** [comment]
Thanks for reporting this, @Saltibarsciai ! The problem seems to me to be that during the `mounted` event of your app component, the `LMap` hasn't yet finished loading Leaflet and creating the map. If you simply change `this.testVersion020();` in the `mounted` handler to `setTimeout(this.testVersion020, 1000);`, you should see the `leafletObject` working as expected, and scroll-wheel zooming getting disabled.

Obviously this isn't a long-term solution though. I think an event emitted by the `LMap` component once it is ready and `leafletObject` is properly available is likely the best solution. I'll add a `ready` event, following the name used for the same thing in [Vue2Leaflet](https://github.com/vue-leaflet/Vue2Leaflet/blob/master/src/components/LMap.vue#L220-L227).

**Comment by Saltibarsciai** [comment]
@mikeu Thanks, I hope your pull request will be approved! DonNico in doscord said he'll check LPopup and marker ref today, hopefully he'll come up with pull request as well 🥇
