### ISSUE TITLE
How to set the <LMarker> riseOnHover option?

### ISSUE THREAD

**Issue by helenmoon1** [vue-leaflet/vue-leaflet#56]
Does vue-leaflet have no options prop?  
`<LMarker :options="{riseOnHover: true, riseOffset: 300}"/>`， Vue2-leaflet style doesn't seem to work.

**Comment by mikeu** [comment]
@helenmoon1 thank you for raising this issue! It turns out that through a slight oversight in rewriting/converting from the Vue2Leaflet code base, we have simply not yet hooked up the passing of additional options not covered by `props`. It's definitely in the plan to do so though, before too long. We'll update you here once it's ready.

**Comment by helenmoon1** [comment]
@mikeu Thank you for your reply. Looking forward to updates on this.
