### ISSUE TITLE
leaflet-editable and leaflet.markercluster

### ISSUE THREAD

**Issue by astrotrain55** [vue-leaflet/vue-leaflet#94]
1. Do you plan to add functionality of leaflet-editable and leaflet.markercluster plugins?
2. Did you intentionally make this package incompatible with vue2-leaflet so that existing plugins for it would fall off?

**Comment by mikeu** [comment]
>     1. Do you plan to add functionality of leaflet-editable and leaflet.markercluster plugins?

Just as with Vue2Leaflet, we do not plan to include any plugins in this library, though we are happy to add links to any that are developed by the community.

>     2. Did you intentionally make this package incompatible with vue2-leaflet so that existing plugins for it would fall off?

We intentionally chose to add functionality and features that are incompatible with Vue2Leaflet, which is why this is a separate package and library, targeting a new major release of Vue.

**Comment by Eternal-Rise** [comment]
@mikeu , are there currently any plugins that have been ported to Vue 3?
