### ISSUE TITLE
Using LWmsTileLayer 

### ISSUE THREAD

**Issue by parkb83** [vue-leaflet/vue-leaflet#96]
Hi, great library and thanks for all of you hard work!

Is there an example for LWmsTileLayer available, I think I must be doing something wrong when passing through the layer name as an option.

Thanks
Brett

**Comment by mikeu** [comment]
Thanks, @parkb83 !

I've just added a PR to get the WMS tile layer example into the demo playground. In the meantime before it's approved, you can check out the code at https://github.com/vue-leaflet/vue-leaflet/tree/add-wms-tile-layer-example, or maybe this example will be enough to get you going:
```vue
<l-wms-tile-layer
  base-url="https://maps.heigit.org/osm-wms/service"
  attribution="HeiGIT <a href='osm-wms.de'>OSM WMS</a>"
  layer-type="base"
  name="osm-wms.de"
  :max-zoom="10"
  version="1.3.0"
  format="image/png"
  transparent="true"
  layers="osm_auto:all"
/>
```

If that's still not working for you, feel free to reply with a code example of what you're trying that isn't working!

**Comment by parkb83** [comment]
Hi mikeu,

Thanks for this, I had a play with this last night and managed to get your example working which is great! Although when try to use a different mapping provider, I get an unauthorised response when trying to send my apikey.

Specifically the example I am trying to implement follow the example in the link below.

https://labs.os.uk/public/os-data-hub-examples/os-maps-api/wmts-3857-basic-map

Thanks for your help

**Comment by mikeu** [comment]
@parkb83 not sure exactly what you've tried, and I didn't sign up for an api key myself there to test, but taking a look at the docs you referenced, something like the code below might get you a little closer. It appears as if they use a few slightly non-standard configuration options, which is why they have to build a custom query string instead of simply passing options to the layer component, but hopefully this helps.

Add the component in your map:
```vue
<l-wms-tile-layer
  layer-type="base"
  name="ordnanceSurvey"
  :base-url="osMapUrl"
  version="2.0.0"
/>
```
This might also want `:tms="true"` I'm not sure, try adding that if the map generally works but the tiles seem to be in the wrong order.

And set up the url with something like this, based on the example you mentioned:
```js
export default {
  // ...components, props, etc...
  data() {
    const osMapBase = "https://api.os.uk/maps/raster/v1/wmts";
    const osMapParams = {
      key: "yourApiKey",
      service: "WMTS",
      outputFormat: "image/png",
      style: "default",
      layer: "Light_3857",
      tileMatrixSet: "EPSG:3857",
      tileMatrix: "{z}",
      tileRow: "{y}",
      tileCol: "{x}",
    };
    const osMapQuery = Object.keys(osMapParams)
      .map((key) => `${key}=${osMapParams[key]}`)
      .join("&");
    const osMapUrl = `${osMapBase}?${osMapQuery}`;

    return {
      osMapUrl,
    };
  },
}
```
